# Generated by Django 4.2.1 on 2023-07-13 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopicModelForm',
            fields=[
                ('Topic_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WebpageModlForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Url', models.URLField()),
                ('Topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.topicmodelform')),
            ],
        ),
        migrations.CreateModel(
            name='AccessrecordModelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.IntegerField(max_length=10)),
                ('Author', models.CharField(max_length=100)),
                ('Nme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.webpagemodlform')),
            ],
        ),
    ]
